"""add phone number column to users table

Revision ID: 269c21fc1f11
Revises: 9cf06642f2f0
Create Date: 2024-05-02 12:23:44.935473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '269c21fc1f11'
down_revision = '9cf06642f2f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=40), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
