"""revise user model

Revision ID: 797b6e41ef73
Revises: a248ba3da3b1
Create Date: 2024-04-18 00:02:55.981796

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '797b6e41ef73'
down_revision = 'a248ba3da3b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint('email', ['email'])
        batch_op.create_unique_constraint('username', ['username'])
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint('email', type_='unique')
        batch_op.drop_constraint('username', type_='unique')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
