"""add price column to Car model

Revision ID: 7b2654c4c0b2
Revises: d5cfd9018eca
Create Date: 2024-04-27 16:55:05.170820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2654c4c0b2'
down_revision = 'd5cfd9018eca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
