"""revise column cars table

Revision ID: 969b7419735c
Revises: d42533a9d49f
Create Date: 2024-04-08 15:40:45.875950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '969b7419735c'
down_revision = 'd42533a9d49f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.String(length=255), nullable=False))
        batch_op.drop_column('car_type')
        batch_op.drop_column('seat_number')
        batch_op.drop_column('door_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('door_number', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('seat_number', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('car_type', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('year')

    # ### end Alembic commands ###
