"""Modify the column attribute on users table

Revision ID: 9e67ed6d43ac
Revises: 269c21fc1f11
Create Date: 2024-05-03 09:53:17.768403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e67ed6d43ac'
down_revision = '269c21fc1f11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)

    # ### end Alembic commands ###
