"""create cars table

Revision ID: d42533a9d49f
Revises: 5613800a0c48
Create Date: 2024-04-08 11:14:48.341891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42533a9d49f'
down_revision = '5613800a0c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('seat', sa.Integer(), nullable=False),
    sa.Column('door', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=255), nullable=False),
    sa.Column('displacement', sa.String(length=255), nullable=False),
    sa.Column('car_type', sa.String(length=255), nullable=False),
    sa.Column('seat_number', sa.String(length=255), nullable=False),
    sa.Column('door_number', sa.String(length=255), nullable=False),
    sa.Column('car_length', sa.String(length=255), nullable=False),
    sa.Column('wheelbase', sa.String(length=255), nullable=False),
    sa.Column('power_type', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    # ### end Alembic commands ###
