"""add auto_code to reservation table for payment success

Revision ID: d7f46cb373ce
Revises: beca58e78f20
Create Date: 2024-04-30 00:19:02.629965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7f46cb373ce'
down_revision = 'beca58e78f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_code', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('auth_code')

    # ### end Alembic commands ###
